# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SuinoAlpha
                                 A QGIS plugin
 Plugin para dimensionamento de suinocultura.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-18
        copyright            : (C) 2025 by Adriano Lopes Godoy - EPP
        email                : adriano.godoy@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SuinoAlpha class from file SuinoAlpha.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .suino_alpha import SuinoAlpha
    return SuinoAlpha(iface)
