# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SuinoAlpha
                                 A QGIS plugin
 Plugin para dimensionamento de suinocultura.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-18
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Adriano Lopes Godoy - EPP
        email                : adriano.godoy@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .suino_alpha_dialog import SuinoAlphaDialog
import os.path


class SuinoAlpha:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SuinoAlpha_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&SuinoAlpha')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SuinoAlpha', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        icon_size=None,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        # If a specific size is requested, render a scaled pixmap and use that
        if icon_size is not None:
            try:
                pix = icon.pixmap(icon_size, icon_size)
                icon = QIcon(pix)
            except Exception:
                # fallback: keep original icon
                pass
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/suino_alpha/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Suinocultura'),
            callback=self.run,
            icon_size=24,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&SuinoAlpha'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = SuinoAlphaDialog(self.iface)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Get values from the dialog
            num_galpoes = self.dlg.spinBox_num_galpoes.value()
            suinos_por_galpao = self.dlg.spinBox_suinos_por_galpao.value()
            espacamento = self.dlg.doubleSpinBox_espacamento.value()
            coord_x = self.dlg.doubleSpinBox_coord_x.value()
            coord_y = self.dlg.doubleSpinBox_coord_y.value()
            orientacao = self.dlg.doubleSpinBox_orientacao.value()
            output_path = self.dlg.lineEdit_output_path.text()
            tipo_galpao = self.dlg.comboBox_tipo_galpao.currentText()

            largura = 12.0
            comprimento = 100.0

            if tipo_galpao == "Galpão New Design 120 m x 20 m":
                largura = 20.0
                comprimento = 120.0
            
            # Validate output path
            if not output_path:
                self.iface.messageBar().pushMessage(
                    "Erro",
                    "Por favor, selecione um arquivo de saída!",
                    level=1,
                    duration=3
                )
                return
            
            # Create the geometries
            self.create_galpoes_layer(
                num_galpoes, suinos_por_galpao, espacamento,
                largura, comprimento, coord_x, coord_y,
                orientacao, output_path
            )
    
    def create_galpoes_layer(self, num_galpoes, suinos_por_galpao, espacamento,
                            largura, comprimento, coord_x, coord_y,
                            orientacao, output_path):
        """Create shapefile with pig barn geometries."""
        from qgis.core import (QgsVectorLayer, QgsFeature, QgsGeometry, 
                              QgsPointXY, QgsField, QgsVectorFileWriter,
                              QgsCoordinateReferenceSystem, QgsProject,
                              QgsCoordinateTransform, QgsUnitTypes)
        from qgis.PyQt.QtCore import QVariant
        import math
        
        # Obter o sistema de coordenadas do projeto
        project_crs = QgsProject.instance().crs()
        
        # Verificar se o CRS é geográfico (lat/lon) ou projetado (metros)
        is_geographic = project_crs.isGeographic()
        
        # Obter as unidades do mapa
        map_units = project_crs.mapUnits()
        
        # Criar mensagem informativa sobre o sistema de coordenadas
        crs_info = f"CRS do Projeto: {project_crs.authid()} - {project_crs.description()}"
        
        if is_geographic:
            # Sistema geográfico (graus) - precisamos converter metros para graus
            self.iface.messageBar().pushMessage(
                "Aviso",
                f"{crs_info}\n⚠️ Sistema geográfico detectado! As dimensões serão aproximadas.",
                level=1,
                duration=5
            )
            
            # Conversão aproximada: 1 grau ≈ 111km no equador
            # Usar latitude média para melhor precisão
            lat_rad = math.radians(coord_y)
            meters_per_degree_lat = 111132.92 - 559.82 * math.cos(2 * lat_rad) + 1.175 * math.cos(4 * lat_rad)
            meters_per_degree_lon = 111412.84 * math.cos(lat_rad) - 93.5 * math.cos(3 * lat_rad)
            
            # Fator de conversão metros -> graus
            factor_x = 1.0 / meters_per_degree_lon
            factor_y = 1.0 / meters_per_degree_lat
            
        elif map_units == QgsUnitTypes.DistanceMeters:
            # Sistema projetado em metros - ideal!
            self.iface.messageBar().pushMessage(
                "Info",
                f"{crs_info}\n✅ Sistema projetado em metros - dimensões precisas!",
                level=3,
                duration=3
            )
            factor_x = 1.0
            factor_y = 1.0
            
        else:
            # Outras unidades (pés, etc)
            unit_name = QgsUnitTypes.toString(map_units)
            self.iface.messageBar().pushMessage(
                "Aviso",
                f"{crs_info}\n⚠️ Unidades: {unit_name}. Verifique as dimensões!",
                level=1,
                duration=5
            )
            # Assumir metros como padrão e deixar usuário ajustar
            factor_x = 1.0
            factor_y = 1.0
        
        # Criar camada de memória com o CRS do projeto
        layer = QgsVectorLayer(f'Polygon?crs={project_crs.authid()}', 'Galpões', 'memory')
        provider = layer.dataProvider()
        
        # Adicionar campos de atributos
        provider.addAttributes([
            QgsField('id_galpao', QVariant.Int),
            QgsField('capacidade', QVariant.Int),
            QgsField('tipo_bebedouro', QVariant.String),
            QgsField('tipo_comedouro', QVariant.String),
            QgsField('largura_m', QVariant.Double),
            QgsField('comprim_m', QVariant.Double),
            QgsField('area_m2', QVariant.Double),
            QgsField('crs', QVariant.String),
            QgsField('observacao', QVariant.String)
        ])
        layer.updateFields()
        
        # Calculate total animals
        total_suinos = num_galpoes * suinos_por_galpao
        
        # Convert orientation to radians
        angle_rad = math.radians(orientacao)
        
        # Aplicar fatores de conversão às dimensões (metros -> unidades do mapa)
        largura_mapa = largura * factor_x
        comprimento_mapa = comprimento * factor_x  # Usar factor_x para comprimento horizontal
        espacamento_mapa = espacamento * factor_x
        
        # Create features for each barn
        features = []
        for i in range(num_galpoes):
            # Calculate offset for this barn (perpendicular to orientation)
            offset_distance = i * (largura_mapa + espacamento_mapa)
            
            # Calculate offset in x and y based on orientation
            # Barns are placed perpendicular to the main orientation
            offset_x = offset_distance * math.cos(angle_rad + math.pi/2)
            offset_y = offset_distance * math.sin(angle_rad + math.pi/2)
            
            # Base point for this barn
            base_x = coord_x + offset_x
            base_y = coord_y + offset_y
            
            # Create rectangle corners (barn aligned with orientation)
            # Corner 1 (bottom-left)
            x1 = base_x
            y1 = base_y
            
            # Corner 2 (bottom-right) - along length
            x2 = base_x + comprimento_mapa * math.cos(angle_rad)
            y2 = base_y + comprimento_mapa * math.sin(angle_rad)
            
            # Corner 3 (top-right) - along width
            x3 = x2 + largura_mapa * math.cos(angle_rad + math.pi/2)
            y3 = y2 + largura_mapa * math.sin(angle_rad + math.pi/2)
            
            # Corner 4 (top-left)
            x4 = x1 + largura_mapa * math.cos(angle_rad + math.pi/2)
            y4 = y1 + largura_mapa * math.sin(angle_rad + math.pi/2)
            
            # Create polygon geometry
            points = [
                QgsPointXY(x1, y1),
                QgsPointXY(x2, y2),
                QgsPointXY(x3, y3),
                QgsPointXY(x4, y4),
                QgsPointXY(x1, y1)  # Close the polygon
            ]
            
            # Create feature
            feature = QgsFeature()
            feature.setGeometry(QgsGeometry.fromPolygonXY([points]))
            
            # Set attributes (sempre em metros para referência)
            area = largura * comprimento
            feature.setAttributes([
                i + 1,  # id_galpao
                suinos_por_galpao,  # capacidade
                "chupeta",  # tipo_bebedouro
                "funil",  # tipo_comedouro
                largura,  # largura_m (sempre em metros)
                comprimento,  # comprim_m (sempre em metros)
                area,  # area_m2 (sempre em metros quadrados)
                project_crs.authid(),  # crs
                f"Galpão {i+1} - {suinos_por_galpao} suínos"  # observacao
            ])
            
            features.append(feature)

        
        # Add features to the layer
        provider.addFeatures(features)
        layer.updateExtents()
        
        # Save to shapefile
        error = QgsVectorFileWriter.writeAsVectorFormat(
            layer,
            output_path,
            "UTF-8",
            layer.crs(),
            "ESRI Shapefile"
        )
        
        if error[0] == QgsVectorFileWriter.NoError:
            # Load the saved layer to QGIS
            saved_layer = QgsVectorLayer(output_path, 'Galpões de Suinocultura', 'ogr')
            if saved_layer.isValid():
                QgsProject.instance().addMapLayer(saved_layer)
                
                # Show success message
                self.iface.messageBar().pushMessage(
                    "Sucesso",
                    f"Galpões criados com sucesso! Total de {total_suinos} suínos em {num_galpoes} galpões.",
                    level=3,
                    duration=5
                )
            else:
                self.iface.messageBar().pushMessage(
                    "Erro",
                    "Erro ao carregar a camada criada.",
                    level=2,
                    duration=3
                )
        else:
            self.iface.messageBar().pushMessage(
                "Erro",
                f"Erro ao salvar o shapefile: {error}",
                level=2,
                duration=3
            )

