# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SuinoAlphaDialog
                                 A QGIS plugin
 Plugin para dimensionamento de suinocultura.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-18
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Adriano Lopes Godoy - EPP
        email                : adriano.godoy@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QFileDialog
from qgis.PyQt.QtCore import pyqtSignal
from qgis.gui import QgsMapToolEmitPoint
from qgis.core import QgsPointXY

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'suino_alpha_dialog_base.ui'))


class PointMapTool(QgsMapToolEmitPoint):
    """Map tool para capturar um ponto clicado no mapa."""
    
    def __init__(self, canvas):
        QgsMapToolEmitPoint.__init__(self, canvas)
        self.canvas = canvas
        self.point = None
    
    def canvasReleaseEvent(self, event):
        """Captura o ponto quando o usuário clica no mapa."""
        # Pega a posição do clique no sistema de coordenadas do mapa
        self.point = self.toMapCoordinates(event.pos())
        # Emite o sinal com o ponto
        self.canvasClicked.emit(self.point, event.button())


class SuinoAlphaDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, iface, parent=None):
        """Constructor."""
        super(SuinoAlphaDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # Salvar referência à interface do QGIS
        self.iface = iface
        self.canvas = iface.mapCanvas()
        self.point_tool = None
        self.previous_map_tool = None
        
        # Connect the browse button to select output file
        self.pushButton_browse.clicked.connect(self.select_output_file)
        
        # Connect the select point button
        self.pushButton_select_point.clicked.connect(self.select_point_on_map)
    
    def select_output_file(self):
        """Open file dialog to select output shapefile path."""
        filename, _ = QFileDialog.getSaveFileName(
            self,
            "Selecionar arquivo de saída",
            "",
            "Shapefile (*.shp)"
        )
        if filename:
            self.lineEdit_output_path.setText(filename)
    
    def select_point_on_map(self):
        """Ativa a ferramenta para selecionar um ponto no mapa."""
        # Criar a ferramenta de seleção de ponto se ainda não existe
        if not self.point_tool:
            self.point_tool = PointMapTool(self.canvas)
            self.point_tool.canvasClicked.connect(self.point_selected)
        
        # Salvar a ferramenta atual para restaurar depois
        self.previous_map_tool = self.canvas.mapTool()
        
        # Ativar nossa ferramenta de seleção
        self.canvas.setMapTool(self.point_tool)
        
        # Minimizar o diálogo para facilitar a visualização do mapa
        self.showMinimized()
        
        # Alterar o texto do botão para indicar que está aguardando
        self.pushButton_select_point.setText("⏳ Clique no mapa...")
        self.pushButton_select_point.setEnabled(False)
    
    def point_selected(self, point, button):
        """Callback quando um ponto é selecionado no mapa."""
        # Atualizar os campos de coordenadas com o ponto selecionado
        self.doubleSpinBox_coord_x.setValue(point.x())
        self.doubleSpinBox_coord_y.setValue(point.y())
        
        # Restaurar a ferramenta anterior
        if self.previous_map_tool:
            self.canvas.setMapTool(self.previous_map_tool)
        
        # Restaurar o diálogo
        self.showNormal()
        self.activateWindow()
        
        # Restaurar o botão
        self.pushButton_select_point.setText("📍 Clique no Mapa para Selecionar Posição")
        self.pushButton_select_point.setEnabled(True)
        
        # Mostrar mensagem de confirmação
        self.iface.messageBar().pushMessage(
            "Posição Selecionada",
            f"Coordenadas: X={point.x():.6f}, Y={point.y():.6f}",
            level=3,
            duration=3
        )
    
    def closeEvent(self, event):
        """Restaurar a ferramenta do mapa quando o diálogo é fechado."""
        if self.previous_map_tool and self.canvas.mapTool() == self.point_tool:
            self.canvas.setMapTool(self.previous_map_tool)
        event.accept()

