# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SuinoAlphaDialog
                                 A QGIS plugin
 Plugin para dimensionamento de suinocultura.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-18
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Adriano Lopes Godoy - EPP
        email                : adriano.godoy@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from datetime import datetime

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QFileDialog, QMessageBox
from qgis.gui import QgsMapToolEmitPoint
from qgis.core import QgsMessageLog, Qgis

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'suino_alpha_dialog_base.ui'))


class PointMapTool(QgsMapToolEmitPoint):
    """Map tool para capturar um ponto clicado no mapa."""
    
    def __init__(self, canvas):
        QgsMapToolEmitPoint.__init__(self, canvas)
        self.canvas = canvas
        self.point = None
    
    def canvasReleaseEvent(self, event):
        """Captura o ponto quando o usuário clica no mapa."""
        # Pega a posição do clique no sistema de coordenadas do mapa
        self.point = self.toMapCoordinates(event.pos())
        # Emite o sinal com o ponto
        self.canvasClicked.emit(self.point, event.button())


class SuinoAlphaDialog(QtWidgets.QDialog, FORM_CLASS):
    """Diálogo principal do plugin."""

    PRODUCTION_SYSTEMS = {
        "Ciclo Completo (CC)": {
            "effluent_m3_day": 0.0471,
            "p2o5_kg_year": 49.6,
            "description": "Sistema completo com todas as fases produtivas"
        },
        "Unidade de Produção de Leitões (UPL)": {
            "effluent_m3_day": 0.0228,
            "p2o5_kg_year": 18.0,
            "description": "Produção até leitões 25 kg"
        },
        "Unidade de Produção de Desmamados (UPD)": {
            "effluent_m3_day": 0.0162,
            "p2o5_kg_year": 8.5,
            "description": "Fase pós-desmame até 25 kg"
        },
        "Crechário (CR)": {
            "effluent_m3_day": 0.0023,
            "p2o5_kg_year": 0.25,
            "description": "Animais na fase de creche"
        },
        "Unidade de Terminação (UT)": {
            "effluent_m3_day": 0.0130,
            "p2o5_kg_year": 4.3,
            "description": "Animais de terminação 23-120 kg"
        }
    }

    PLANT_P2O5_REQUIREMENT = {
        "Pastagem": 45.0,
        "Soja": 80.0,
        "Milho": 90.0
    }

    def __init__(self, iface, parent=None):
        """Constructor."""
        super(SuinoAlphaDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # Salvar referência à interface do QGIS
        self.iface = iface
        self.canvas = iface.mapCanvas()
        self.point_tool = None
        self.previous_map_tool = None
        self._auto_updating_total = False
        
        # Connect the browse button to select output file
        self.pushButton_browse.clicked.connect(self.select_output_file)
        
        # Connect the select point button
        self.pushButton_select_point.clicked.connect(self.select_point_on_map)

        # Dimensionamento handlers
        self.comboBox_sistema_producao.currentTextChanged.connect(self.update_effluent_defaults)
        self.spinBox_num_galpoes.valueChanged.connect(self.update_total_animais)
        self.spinBox_suinos_por_galpao.valueChanged.connect(self.update_total_animais)
        self.pushButton_generate_report.clicked.connect(self.on_generate_report_clicked)

        # Inicializar campos com valores coerentes
        self.update_total_animais()
        self.update_effluent_defaults()
    
    def select_output_file(self):
        """Open file dialog to select output shapefile path."""
        filename, _ = QFileDialog.getSaveFileName(
            self,
            "Selecionar arquivo de saída",
            "",
            "Shapefile (*.shp)"
        )
        if filename:
            self.lineEdit_output_path.setText(filename)
    
    def select_point_on_map(self):
        """Ativa a ferramenta para selecionar um ponto no mapa."""
        # Criar a ferramenta de seleção de ponto se ainda não existe
        if not self.point_tool:
            self.point_tool = PointMapTool(self.canvas)
            self.point_tool.canvasClicked.connect(self.point_selected)
        
        # Salvar a ferramenta atual para restaurar depois
        self.previous_map_tool = self.canvas.mapTool()
        
        # Ativar nossa ferramenta de seleção
        self.canvas.setMapTool(self.point_tool)
        
        # Minimizar o diálogo para facilitar a visualização do mapa
        self.showMinimized()
        
        # Alterar o texto do botão para indicar que está aguardando
        self.pushButton_select_point.setText("⏳ Clique no mapa...")
        self.pushButton_select_point.setEnabled(False)
    
    def point_selected(self, point, button):
        """Callback quando um ponto é selecionado no mapa."""
        # Atualizar os campos de coordenadas com o ponto selecionado
        self.doubleSpinBox_coord_x.setValue(point.x())
        self.doubleSpinBox_coord_y.setValue(point.y())
        
        # Restaurar a ferramenta anterior
        if self.previous_map_tool:
            self.canvas.setMapTool(self.previous_map_tool)
        
        # Restaurar o diálogo
        self.showNormal()
        self.activateWindow()
        
        # Restaurar o botão
        self.pushButton_select_point.setText("📍 Clique no Mapa para Selecionar Posição")
        self.pushButton_select_point.setEnabled(True)
        
        # Mostrar mensagem de confirmação
        self.iface.messageBar().pushMessage(
            "Posição Selecionada",
            f"Coordenadas: X={point.x():.6f}, Y={point.y():.6f}",
            level=3,
            duration=3
        )
    
    def closeEvent(self, event):
        """Restaurar a ferramenta do mapa quando o diálogo é fechado."""
        if self.previous_map_tool and self.canvas.mapTool() == self.point_tool:
            self.canvas.setMapTool(self.previous_map_tool)
        event.accept()

    # ------------------------------------------------------------------
    # Handlers para dimensionamento
    # ------------------------------------------------------------------

    def update_total_animais(self):
        """Atualiza o total de animais sugerido a partir dos galpões configurados."""
        if self._auto_updating_total:
            return
        total = self.spinBox_num_galpoes.value() * self.spinBox_suinos_por_galpao.value()
        self._auto_updating_total = True
        try:
            self.spinBox_total_animais.setValue(total)
        finally:
            self._auto_updating_total = False

    def update_effluent_defaults(self):
        """Ajusta valores sugeridos conforme o sistema de produção selecionado."""
        sistema = self.comboBox_sistema_producao.currentText()
        data = self.PRODUCTION_SYSTEMS.get(sistema)
        if not data:
            return
        # Atualiza o efluente diário por animal apenas se o usuário não alterou drasticamente
        self.doubleSpinBox_efluente_diario.setValue(round(data["effluent_m3_day"], 4))

    def on_generate_report_clicked(self):
        """Executa cálculo e gera relatório de dimensionamento."""
        total_animais = self.spinBox_total_animais.value()
        if total_animais <= 0:
            QMessageBox.warning(self, "Informação insuficiente", "Informe o total de animais para gerar o relatório.")
            return

        sistema = self.comboBox_sistema_producao.currentText()
        sistema_data = self.PRODUCTION_SYSTEMS.get(sistema)
        if not sistema_data:
            QMessageBox.warning(self, "Sistema inválido", "Selecione um sistema de produção válido.")
            return

        efluente_diario = self.doubleSpinBox_efluente_diario.value()
        trh_biodigestor = self.doubleSpinBox_trh_biodigestor.value()
        trh_total = self.doubleSpinBox_trh_total.value()
        altura_biodigestor = self.doubleSpinBox_altura_biodigestor.value()
        altura_lagoas = self.doubleSpinBox_altura_lagoas.value()

        if trh_total <= trh_biodigestor:
            QMessageBox.warning(
                self,
                "Dados inconsistentes",
                "O TRH total do sistema deve ser maior que o TRH do biodigestor. Ajuste os valores."
            )
            return

        vazao_diaria = total_animais * efluente_diario
        volume_biodigestor = vazao_diaria * trh_biodigestor
        tempo_restante = trh_total - trh_biodigestor
        # Dividir igualmente entre duas lagoas
        trh_lagoa = tempo_restante / 2.0
        if trh_lagoa < 1.0:
            QMessageBox.warning(
                self,
                "TRH insuficiente",
                "Tempo de retenção muito baixo para as lagoas. Aumente o TRH total do sistema."
            )
            return

        volume_lagoa = vazao_diaria * trh_lagoa

        biodigestor_dims = self.solve_frustum_dimensions(volume_biodigestor, altura_biodigestor, ratio=3.0)
        lagoa_dims = self.solve_frustum_dimensions(volume_lagoa, altura_lagoas, ratio=2.0)

        if biodigestor_dims is None or lagoa_dims is None:
            QMessageBox.warning(self, "Geometria inviável", "Não foi possível determinar dimensões coerentes com os parâmetros informados.")
            return

        p2o5_total = total_animais * sistema_data["p2o5_kg_year"]
        areas_fertirrigacao = self.estimate_fertigation_area(p2o5_total)

        report_text = self.build_report(
            sistema=sistema,
            total_animais=total_animais,
            efluente_diario=efluente_diario,
            vazao_diaria=vazao_diaria,
            trh_biodigestor=trh_biodigestor,
            trh_total=trh_total,
            trh_lagoa=trh_lagoa,
            volume_biodigestor=volume_biodigestor,
            volume_lagoa=volume_lagoa,
            biodigestor_dims=biodigestor_dims,
            lagoa_dims=lagoa_dims,
            p2o5_total=p2o5_total,
            areas_fertirrigacao=areas_fertirrigacao,
            sistema_desc=sistema_data.get("description", "")
        )

        # Registrar no log do QGIS para consulta rápida
        QgsMessageLog.logMessage(report_text, "SuinoAlpha", level=Qgis.Info)

        # Exibir janela de resumo breve
        resumo = (
            f"Vazão diária: {vazao_diaria:.2f} m³/dia\n"
            f"Volume biodigestor: {volume_biodigestor:.2f} m³\n"
            f"Volume lagoa (cada): {volume_lagoa:.2f} m³\n"
            f"Área fertirrigada (milho): {areas_fertirrigacao['Milho']:.2f} ha"
        )
        QMessageBox.information(self, "Relatório gerado", resumo)
        # Preparar HTML do relatório
        # Arredondar dimensões das lagoas ao metro mais próximo conforme pedido
        lagoa_dims_rounded = {
            k: (int(round(v)) if isinstance(v, (int, float)) else v)
            for k, v in lagoa_dims.items()
        }

        html = self.build_report_html(
            sistema=sistema,
            total_animais=total_animais,
            efluente_diario=efluente_diario,
            vazao_diaria=vazao_diaria,
            trh_biodigestor=trh_biodigestor,
            trh_total=trh_total,
            trh_lagoa=trh_lagoa,
            volume_biodigestor=volume_biodigestor,
            volume_lagoa=volume_lagoa,
            biodigestor_dims=biodigestor_dims,
            lagoa_dims=lagoa_dims_rounded,
            p2o5_total=p2o5_total,
            areas_fertirrigacao=areas_fertirrigacao,
            sistema_desc=sistema_data.get("description", "")
        )

        # Perguntar se deseja salvar (sugerir HTML)
        filename, _ = QFileDialog.getSaveFileName(
            self,
            "Salvar relatório HTML",
            os.path.splitext(self.default_report_name())[0] + ".html",
            "Página HTML (*.html);;Arquivos de texto (*.txt);;Todos os arquivos (*.*)"
        )
        if filename:
            try:
                with open(filename, "w", encoding="utf-8") as handle:
                    handle.write(html)
                self.iface.messageBar().pushMessage(
                    "Relatório salvo",
                    f"Arquivo gravado em {filename}",
                    level=Qgis.Success,
                    duration=5
                )
            except OSError as exc:
                QMessageBox.critical(self, "Erro ao salvar", f"Não foi possível salvar o relatório:\n{exc}")

    def solve_frustum_dimensions(self, volume, altura, ratio, max_iterations=60):
        """Resolve dimensões de um tronco de pirâmide retangular dado volume e altura."""
        if volume <= 0 or altura <= 0:
            return None

        min_width = 2 * altura + 0.1
        top_width = min_width
        top_length = ratio * top_width

        def frustum_volume(length_top, width_top):
            length_bottom = length_top - 2 * altura
            width_bottom = width_top - 2 * altura
            if length_bottom <= 0 or width_bottom <= 0:
                return None
            return (
                (length_top * width_top)
                + (length_bottom * width_bottom)
                + (length_top + length_bottom) * (width_top + width_bottom)
            ) * altura / 6.0

        # Expand upper bound até cobrir o volume
        hi = top_width
        current_volume = frustum_volume(ratio * hi, hi)
        if current_volume is None:
            # altura incompatível com dimensões mínimas
            return None
        iterations = 0
        while current_volume < volume and iterations < max_iterations:
            hi *= 1.4
            current_volume = frustum_volume(ratio * hi, hi)
            if current_volume is None:
                return None
            iterations += 1
        if current_volume < volume:
            return None

        lo = min_width
        for _ in range(max_iterations):
            mid = (lo + hi) / 2.0
            mid_volume = frustum_volume(ratio * mid, mid)
            if mid_volume is None:
                return None
            if abs(mid_volume - volume) < 1e-3:
                top_width = mid
                break
            if mid_volume < volume:
                lo = mid
            else:
                hi = mid
            top_width = mid

        top_length = ratio * top_width
        base_length = top_length - 2 * altura
        base_width = top_width - 2 * altura
        return {
            "top_length": top_length,
            "top_width": top_width,
            "base_length": base_length,
            "base_width": base_width,
            "height": altura
        }

    def estimate_fertigation_area(self, total_p2o5):
        """Calcula área de fertirrigação para culturas selecionadas."""
        areas = {}
        for cultura, demanda in self.PLANT_P2O5_REQUIREMENT.items():
            if demanda <= 0:
                areas[cultura] = 0.0
            else:
                areas[cultura] = total_p2o5 / demanda
        return areas

    def build_report(self, **kwargs):
        """Monta texto do relatório."""
        areas = kwargs.get("areas_fertirrigacao", {})
        lines = [
            "# Relatório de Dimensionamento de Tratamento",
            "",
            f"Data: {datetime.now().strftime('%d/%m/%Y %H:%M')}",
            f"Sistema de produção: {kwargs.get('sistema')} ({kwargs.get('sistema_desc', '')})",
            f"Total de animais: {kwargs.get('total_animais')}",
            "",
            "## Parâmetros de entrada",
            f"- Efluente adotado: {kwargs.get('efluente_diario'):.4f} m³/suíno/dia",
            f"- Vazão diária total: {kwargs.get('vazao_diaria'):.2f} m³/dia",
            f"- TRH biodigestor: {kwargs.get('trh_biodigestor'):.1f} dias",
            f"- TRH total do sistema: {kwargs.get('trh_total'):.0f} dias",
            f"- TRH por lagoa: {kwargs.get('trh_lagoa'):.1f} dias",
            "",
            "## Dimensionamento do biodigestor",
            f"- Volume útil: {kwargs.get('volume_biodigestor'):.2f} m³",
            f"- Dimensões topo (L x W): {kwargs['biodigestor_dims']['top_length']:.2f} m x {kwargs['biodigestor_dims']['top_width']:.2f} m",
            f"- Dimensões base (L x W): {kwargs['biodigestor_dims']['base_length']:.2f} m x {kwargs['biodigestor_dims']['base_width']:.2f} m",
            f"- Altura útil: {kwargs['biodigestor_dims']['height']:.2f} m",
            "",
            "## Dimensionamento das lagoas (cada lagoa)",
            f"- Volume útil: {kwargs.get('volume_lagoa'):.2f} m³",
            f"- Dimensões topo (L x W): {kwargs['lagoa_dims']['top_length']:.2f} m x {kwargs['lagoa_dims']['top_width']:.2f} m",
            f"- Dimensões base (L x W): {kwargs['lagoa_dims']['base_length']:.2f} m x {kwargs['lagoa_dims']['base_width']:.2f} m",
            f"- Altura útil: {kwargs['lagoa_dims']['height']:.2f} m",
            "",
            "## Nutrientes e fertirrigação",
            f"- Produção anual estimada de P2O5: {kwargs.get('p2o5_total'):.2f} kg",
        ]

        for cultura, area in areas.items():
            lines.append(f"- Área necessária para {cultura}: {area:.2f} ha")

        lines.extend([
            "",
            "Notas:",
            "1. Volumes calculados assumem tanques retangulares com taludes 1V:1H.",
            "2. Ajustes finos devem considerar normas locais e coeficientes específicos.",
            "3. Exportar o relatório novamente após alterar qualquer parâmetro de entrada.",
        ])

        return "\n".join(lines)

    def build_report_html(self, **kwargs):
        """Monta um relatório em HTML com os resultados do dimensionamento.

        Recebe os mesmos argumentos que build_report (dicionário em kwargs).
        """
        sistema = kwargs.get('sistema')
        sistema_desc = kwargs.get('sistema_desc', '')
        total_animais = kwargs.get('total_animais')
        efluente_diario = kwargs.get('efluente_diario')
        vazao_diaria = kwargs.get('vazao_diaria')
        trh_biodigestor = kwargs.get('trh_biodigestor')
        trh_total = kwargs.get('trh_total')
        trh_lagoa = kwargs.get('trh_lagoa')
        volume_biodigestor = kwargs.get('volume_biodigestor')
        volume_lagoa = kwargs.get('volume_lagoa')
        biodigestor_dims = kwargs.get('biodigestor_dims', {})
        lagoa_dims = kwargs.get('lagoa_dims', {})
        p2o5_total = kwargs.get('p2o5_total')
        areas = kwargs.get('areas_fertirrigacao', {})

        # Pequeno estilo para legibilidade
        style = (
            "body { font-family: Arial, Helvetica, sans-serif; font-size: 14px; }"
            "h1,h2 { color: #2b6ca3; }"
            "table { border-collapse: collapse; width: 100%; margin-bottom: 1em; }"
            "th,td { border: 1px solid #ccc; padding: 6px; text-align: left; }"
            "th { background: #f2f7fb; }"
        )

        html_lines = [
            '<!doctype html>',
            '<html lang="pt-BR">',
            '<head>',
            '<meta charset="utf-8"/>',
            f'<title>Relatório de Dimensionamento - {sistema}</title>',
            f'<style>{style}</style>',
            '</head>',
            '<body>',
            f'<h1>Relatório de Dimensionamento de Tratamento</h1>',
            f'<p><strong>Data:</strong> {datetime.now().strftime("%d/%m/%Y %H:%M")}</p>',
            f'<p><strong>Sistema de produção:</strong> {sistema} - {sistema_desc}</p>',
            f'<p><strong>Total de animais:</strong> {total_animais}</p>',
            '<h2>Parâmetros de entrada</h2>',
            '<table>',
            '<tr><th>Parâmetro</th><th>Valor</th></tr>',
            f'<tr><td>Efluente adotado</td><td>{efluente_diario:.4f} m³/suíno/dia</td></tr>',
            f'<tr><td>Vazão diária total</td><td>{vazao_diaria:.2f} m³/dia</td></tr>',
            f'<tr><td>TRH biodigestor</td><td>{trh_biodigestor:.1f} dias</td></tr>',
            f'<tr><td>TRH total do sistema</td><td>{trh_total:.0f} dias</td></tr>',
            f'<tr><td>TRH por lagoa</td><td>{trh_lagoa:.1f} dias</td></tr>',
            '</table>',
            '<h2>Dimensionamento do biodigestor</h2>',
            '<table>',
            '<tr><th>Item</th><th>Valor</th></tr>',
            f'<tr><td>Volume útil</td><td>{volume_biodigestor:.2f} m³</td></tr>',
            f'<tr><td>Dimensões topo (L x W)</td><td>{biodigestor_dims.get("top_length", 0):.2f} m x {biodigestor_dims.get("top_width", 0):.2f} m</td></tr>',
            f'<tr><td>Dimensões base (L x W)</td><td>{biodigestor_dims.get("base_length", 0):.2f} m x {biodigestor_dims.get("base_width", 0):.2f} m</td></tr>',
            f'<tr><td>Altura útil</td><td>{biodigestor_dims.get("height", 0):.2f} m</td></tr>',
            '</table>',
            '<h2>Dimensionamento das lagoas (cada lagoa)</h2>',
            '<table>',
            '<tr><th>Item</th><th>Valor</th></tr>',
            f'<tr><td>Volume útil</td><td>{volume_lagoa:.2f} m³</td></tr>',
            f'<tr><td>Dimensões topo (L x W)</td><td>{lagoa_dims.get("top_length", 0)} m x {lagoa_dims.get("top_width", 0)} m</td></tr>',
            f'<tr><td>Dimensões base (L x W)</td><td>{lagoa_dims.get("base_length", 0)} m x {lagoa_dims.get("base_width", 0)} m</td></tr>',
            f'<tr><td>Altura útil</td><td>{lagoa_dims.get("height", 0)} m</td></tr>',
            '</table>',
            '<h2>Nutrientes e fertirrigação</h2>',
            '<table>',
            '<tr><th>Item</th><th>Valor</th></tr>',
            f'<tr><td>Produção anual estimada de P2O5</td><td>{p2o5_total:.2f} kg</td></tr>',
        ]

        # Áreas por cultura
        html_lines.append('</table>')
        html_lines.append('<h3>Áreas estimadas por cultura</h3>')
        html_lines.append('<table>')
        html_lines.append('<tr><th>Cultura</th><th>Área necessária (ha)</th></tr>')
        for cultura, area in areas.items():
            html_lines.append(f'<tr><td>{cultura}</td><td>{area:.2f}</td></tr>')
        html_lines.append('</table>')

        html_lines.extend([
            '<h3>Notas</h3>',
            '<ul>',
            '<li>Volumes calculados assumem tanques retangulares com taludes 1V:1H.</li>',
            '<li>Dimensões das lagoas foram arredondadas ao metro mais próximo para fins construtivos.</li>',
            '<li>Ajustes finos devem considerar normas locais e coeficientes específicos.</li>',
            '</ul>',
            '</body>',
            '</html>'
        ])

        return "\n".join(html_lines)

    def default_report_name(self):
        """Sugere nome de arquivo para o relatório."""
        base = datetime.now().strftime("relatorio_tratamento_%Y%m%d_%H%M")
        return os.path.join(os.path.expanduser("~"), f"{base}.txt")

